name: Generate Contribution Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/github-contribution-snake.svg?palette=github-dark&color_snake=#7FC97F

      - name: Commit snake
        uses: EndBug/add-and-commit@v9
        with:
          add: "assets/github-contribution-snake.svg"
          message: "chore: update contribution snake"
